version: '3'

# This file extends docker-compose-mediators.yml

services:
  core-mediator:
    environment:
      NGROK_NAME: core-ngrok
    entrypoint: ./scripts/ngrok-wait.sh
    depends_on: [core-ngrok]

  core-ngrok:
    image: wernight/ngrok
    command: ngrok http -bind-tls=true --log stdout core-mediator:3001
    networks:
      - hyperledger

  # bob-mediator:
  #   environment:
  #     NGROK_NAME: bob-ngrok
  #   entrypoint: ./scripts/ngrok-wait.sh
  #   depends_on: [bob-ngrok]

  # bob-ngrok:
  #   image: wernight/ngrok
  #   command: ngrok http -bind-tls=true --log stdout bob-mediator:3002
  #   networks:
  #     - hyperledger

networks:
  hyperledger:
