#!/bin/bash

AGENT="$1"
YARN_COMMAND=yarn
echo "AGENT DECLARATION"
echo AGENT


AGENT_ENDPOINT="${AGENT_ENDPOINT:-http://localhost:3001}"
AGENT_HOST=http://localhost
AGENT_PORT=3001
AGENT_LABEL=RoutingMediator01
WALLET_NAME=mediator01
WALLET_KEY=0000000000000000000000000Mediator01
PUBLIC_DID=DtWRdd6C5dN5vpcN6XRAvu
PUBLIC_DID_SEED=00000000000000000000000Forward01




# Docker image already compiles. Not needed to do again
${YARN_COMMAND} prod:build


AGENT_ENDPOINT=${AGENT_ENDPOINT} AGENT_HOST=${AGENT_HOST} AGENT_PORT=${AGENT_PORT} AGENT_LABEL=${AGENT_LABEL} WALLET_NAME=${WALLET_NAME} WALLET_KEY=${WALLET_KEY} PUBLIC_DID=${PUBLIC_DID} PUBLIC_DID_SEED=${PUBLIC_DID_SEED} ${YARN_COMMAND} prod:debug
